In [182]:
import sympy as sp
import numpy as np
from scipy.linalg import null_space
import sklearn as sl
import math

In [130]:
N = 227179
B = 50
#B = math.ceil(math.e**(.5*(math.log(N)*math.log(math.log(N)))**.5))
#print(B)

In [131]:
# creates the factor base of N up to B

def eulersCriterion(n, p):
    n = n % p

    for x in range(2, p, 1):
        if ((x * x) % p == n):
            return True
    return False

def factorBase(n, b):

    prime = [True for i in range(n+1)] 

    p = 2
    while(p * p <= n):
        if (prime[p] == True):
            
            for i in range(p * p, n + 1, p):
                prime[i] = False
        p += 1
    
    c = []
    for p in range(2, b):

        if prime[p] and eulersCriterion(n, p):
            c.append(p)
            
    if 2 not in c: c.insert(0, 2)
    return c

print(factorBase(N, B))

[2, 3, 5, 7, 13, 17, 23, 29, 37, 41, 43, 47]


In [199]:
#find smooth numbers using Tonelli–Shanks algorithm and create matrix with rows as smooth numbers

#these variables are subject to optimization
maxSeq = 20 #size of number sequence collected using x^2 - N
maxPow = 3 #max power of the factor base primes
x = math.ceil(N**.5)
fb = factorBase(N, B)

#number sequence
a = []
for i in range(maxSeq):
    a.append((x + i)**2 - N)
print(a)

#exponent matrix (mat[row][col])
rows = len(a)
cols = len(fb)
mat = [[0 for _ in range(cols)] for _ in range(rows)]
#print(mat)

#initial matrix
for i in range(1, maxPow + 1): #power of factor base prime
    for p in range(len(fb)): #prime
        #print(nSolve(p**i), p**i)
        
        for j in nSolve(fb[p]**i): #starting sequence number
            for k in range(j, maxSeq, fb[p]**i): #sequence number
                a[k] = a[k] / fb[p]
                if k < rows and p < cols: 
                    mat[k][p] = mat[k][p] + 1
                    #mat[k][p] = 0 if mat[k][p] % 2 == 0 else 1
        #print(a)
print(a)
#print(mat)



smoothM = [] #smooth number exp matrix
for i in range(len(a)):
    if a[i] == 1: smoothM.append(mat[i])      

smoothM = np.array(smoothM)
smoothMt = smoothM.transpose()
ns = null_space(smoothMt)
print(smoothM)
print(smoothMt)
print(ns)

#smoothM = Matrix(smoothM)
#print(smoothM)

#Need to figure out the nullspace
#print(smoothM.nullspace())
#smoothMt = smoothM.transpose()
#print(smoothMt)
#print(smoothMt.nullspace())
#smoothMt = smoothMt.nullspace()

#print(smoothMt)
#print(smoothM.transpose())
#print(smoothM.nullspace())



[350, 1305, 2262, 3221, 4182, 5145, 6110, 7077, 8046, 9017, 9990, 10965, 11942, 12921, 13902, 14885, 15870, 16857, 17846, 18837]
[1.0, 1.0, 1.0, 3221, 1.0, 1.0, 1.0, 337.0, 149.0, 9017, 1.0, 1.0, 853.0, 4307.0, 331.0, 229.0, 1.0, 1873.0, 8923.0, 1.0]
[[1 0 2 1 0 0 0 0 0 0 0 0]
 [0 2 1 0 0 0 0 1 0 0 0 0]
 [1 1 0 0 1 0 0 1 0 0 0 0]
 [1 1 0 0 0 1 0 0 0 1 0 0]
 [0 1 1 3 0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 0 0 1]
 [1 3 1 0 0 0 0 0 1 0 0 0]
 [0 1 1 0 0 1 0 0 0 0 1 0]
 [1 1 1 0 0 0 2 0 0 0 0 0]
 [0 2 0 1 1 0 1 0 0 0 0 0]]
[[1 0 1 1 0 1 1 0 1 0]
 [0 2 1 1 1 0 3 1 1 2]
 [2 1 0 0 1 1 1 1 1 0]
 [1 0 0 0 3 0 0 0 0 1]
 [0 0 1 0 0 1 0 0 0 1]
 [0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 2 1]
 [0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0 0]]
[]


In [161]:
#solve for n in (x + n)^2 - N = 0(mod p)
def nSolve(p):
    r = []
    for i in range(p):
        if ((x + i)**2 - N) % p == 0:
            r.append(i)
    return r

In [167]:
#check linear independence (use sympy)
def dependent():
    return True

In [100]:
#find null space of matrix (use sympy)
def nullSpace():
    return ns
